# -*- coding: utf-8 -*-
"""DL assignment_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ziqELjB9_jFQCEtKJ0Kq-aBm9eyx19h3

Total images: 70,000
Training: 60,000
Testing: 10,000
Image size: 28 × 28 pixels
Color: Grayscale (black & white)
Classes: 10 types of clothing

CNN works like:

First layer → detects edges
Second layer → detects patterns
Third layer → detects objects

 So we need more filters later
"""

pip install tensorflow

import tensorflow as tf
from keras.datasets import fashion_mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout, Conv2D, MaxPool2D, Flatten, BatchNormalization
from tensorflow.keras.utils import to_categorical
from keras.callbacks import ReduceLROnPlateau

# ── 1. Load & Preprocess ──────────────────────────────
(X_train, y_train), (X_test, y_test) = fashion_mnist.load_data()

X_train = X_train.reshape(-1,28,28,1).astype('float16') / 255
X_test  = X_test.reshape(-1,28,28,1).astype('float16') / 255

Y_train = to_categorical(y_train, 10)
Y_test  = to_categorical(y_test, 10)

"""CNN"""

import tensorflow as tf
from keras.datasets import fashion_mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout, Conv2D, MaxPool2D, Flatten, BatchNormalization
from tensorflow.keras.utils import to_categorical
from keras.callbacks import ReduceLROnPlateau

# ── 1. Load & Preprocess ──────────────────────────────
(X_train, y_train), (X_test, y_test) = fashion_mnist.load_data()

X_train = X_train.reshape(-1,28,28,1).astype('float16') / 255
X_test  = X_test.reshape(-1,28,28,1).astype('float16') / 255

Y_train = to_categorical(y_train, 10)
Y_test  = to_categorical(y_test, 10)

# ── 2. tf.data Pipeline (RAM safe) ───────────────────
def augment(image, label):
    image = tf.image.random_flip_left_right(image)
    image = tf.image.random_brightness(image, 0.1)
    return image, label

train_ds = (tf.data.Dataset.from_tensor_slices((X_train, Y_train))   #Converts your NumPy data into a TensorFlow Dataset Each element = (image, label)
            .shuffle(2000)
            .map(augment, num_parallel_calls=tf.data.AUTOTUNE)    """what num_parallel_calls means How many samples to process at the same time
🤖 What tf.data.AUTOTUNE does
TensorFlow automatically decides:
how many CPU threads to use
based on your system """
            .batch(64)
            .prefetch(tf.data.AUTOTUNE))

test_ds = (tf.data.Dataset.from_tensor_slices((X_test, Y_test))
           .batch(64)
           .prefetch(tf.data.AUTOTUNE))

# ── 3. Lighter Model ──────────────────────────────────
model = Sequential([
    Conv2D(32, (3,3), activation='relu', padding='same', input_shape=(28,28,1)),
    BatchNormalization(),
    MaxPool2D(2,2),
    Dropout(0.25),

    Conv2D(64, (3,3), activation='relu', padding='same'),
    BatchNormalization(),
    MaxPool2D(2,2),
    Dropout(0.25),

    Flatten(),
    Dense(128, activation='relu'),
    BatchNormalization(),
    Dropout(0.4),
    Dense(10, activation='softmax')
])

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

lr_reduce = ReduceLROnPlateau(monitor='val_accuracy', factor=0.5, patience=3)

# ── 4. Train ──────────────────────────────────────────
history = model.fit(train_ds, epochs=25, validation_data=test_ds, callbacks=[lr_reduce])

loss, accuracy = model.evaluate(test_ds)
print("Test Accuracy:", accuracy)

"""Accuracy improved from 87 to 93 %


The model uses a deep CNN with data augmentation, batch normalization, and dropout to achieve stable training, reduce overfitting, and improve classification accuracy.
"""

from keras.models import Sequential
from keras.layers import Conv2D, MaxPool2D, Flatten, Dense, BatchNormalization, Dropout, ZeroPadding2D

model_lenet = Sequential([

    # Block 1 - added padding + BN
    ZeroPadding2D(padding=2),    #ZeroPadding2D adds zeros around the image to preserve spatial dimensions and prevent information loss during convolution. # keeps spatial size
    Conv2D(32, (5,5), activation='relu', input_shape=(28,28,1)),
    BatchNormalization(),
    MaxPool2D(2,2),
    Dropout(0.25),

    # Block 2 - more filters
    Conv2D(64, (3,3), activation='relu', padding='same'),
    BatchNormalization(),
    MaxPool2D(2,2),
    Dropout(0.25),

    # Block 3 - extra conv (LeNet didn't have this)
    Conv2D(128, (3,3), activation='relu', padding='same'),
    BatchNormalization(),
    Dropout(0.25),

    # Classifier
    Flatten(),
    Dense(256, activation='relu'),
    BatchNormalization(),
    Dropout(0.4),
    Dense(84, activation='relu'),     # kept original LeNet dense layer
    Dense(10, activation='softmax')
])

model_lenet.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

model_lenet.fit(
    X_train, Y_train,
    epochs=20,              # more epochs
    batch_size=32,
    validation_data=(X_test, Y_test)
)

loss, acc = model_lenet.evaluate(X_test, Y_test)
print("Upgraded LeNet Accuracy:", acc)

"""upgraded LeNet model improves accuracy by using deeper convolution layers, increased filters, batch normalization for stability, dropout for regularization, and zero padding to preserve spatial information.

***Pre trained models***

LENET🔹 1. Input Layer
Size: 32 × 32 × 1 (grayscale image)


🔹 2. C1 – Convolution Layer
Filters: 6
Kernel: 5×5
Output: 28 × 28 × 6


🔹 3. S2 – Subsampling (Pooling)
Type: Average Pooling
Output: 14 × 14 × 6


🔹 4. C3 – Convolution Layer
Filters: 16
Kernel: 5×5
Output: 10 × 10 × 16


🔹 5. S4 – Subsampling (Pooling)
Output: 5 × 5 × 16


🔹 6. C5 – Convolution Layer
Filters: 120
Kernel: 5×5
Output: 1 × 1 × 120



 (acts like a fully connected layer)

🔹 7. F6 – Fully Connected Layer
Neurons: 84


🔹 8. Output Layer
Neurons: 10 (for digits 0–9)
Activation: Softmax

ALEX NET
"""

import tensorflow as tf
import os

# ── New way to connect for Colab TPU v5e-1 ──
try:
    # Colab TPU v5e-1 uses this env variable
    tpu_address = 'local'  # ← key fix for v5e-1

    resolver = tf.distribute.cluster_resolver.TPUClusterResolver(tpu=tpu_address)
    tf.config.experimental_connect_to_cluster(resolver)
    tf.tpu.experimental.initialize_tpu_system(resolver)
    strategy = tf.distribute.TPUStrategy(resolver)

    print("✅ TPU connected!")
    print("Cores:", strategy.num_replicas_in_sync)

except Exception as e:
    print("❌ Still failing:", e)
    # Fallback to GPU/CPU automatically
    strategy = tf.distribute.get_strategy()
    print("Using fallback:", strategy)

# ==========================================
# STEP 1: TPU Initialization (MUST be first)
# ==========================================
import tensorflow as tf
import os

# Detect and connect to TPU
resolver = tf.distribute.cluster_resolver.TPUClusterResolver()
tf.config.experimental_connect_to_cluster(resolver)
tf.tpu.experimental.initialize_tpu_system(resolver)

# TPU strategy — like GPU mirroring but across TPU cores
strategy = tf.distribute.TPUStrategy(resolver)

print("TPU cores available:", strategy.num_replicas_in_sync)  # Should print 8

# ==========================================
# STEP 2: Data Prep (outside strategy scope)
# ==========================================
from keras.datasets import fashion_mnist
from tensorflow.keras.utils import to_categorical

(X_train, y_train), (X_test, y_test) = fashion_mnist.load_data()

X_train = X_train.reshape(-1,28,28,1).astype('float32') / 255
X_test  = X_test.reshape(-1,28,28,1).astype('float32') / 255

# Resize + RGB
X_train_resized = tf.image.resize(tf.repeat(X_train, 3, axis=-1), (32,32))
X_test_resized  = tf.image.resize(tf.repeat(X_test,  3, axis=-1), (32,32))

Y_train = to_categorical(y_train, 10)
Y_test  = to_categorical(y_test,  10)

# ==========================================
# STEP 3: tf.data Pipeline (TPU requires this)
# ==========================================
# ⚠️ TPU does NOT work with raw numpy arrays
# You MUST use tf.data.Dataset

BATCH_SIZE = 64 * strategy.num_replicas_in_sync  # scale batch by TPU cores (8x)
print("Global batch size:", BATCH_SIZE)           # 512

train_ds = (tf.data.Dataset.from_tensor_slices((X_train_resized, Y_train))
            .shuffle(10000)
            .batch(BATCH_SIZE)
            .prefetch(tf.data.AUTOTUNE))

test_ds = (tf.data.Dataset.from_tensor_slices((X_test_resized, Y_test))
           .batch(BATCH_SIZE)
           .prefetch(tf.data.AUTOTUNE))

# ==========================================
# STEP 4: Build Model INSIDE strategy.scope()
# ==========================================
# ⚠️ This is mandatory for TPU — model must be created inside scope
from keras.layers import Conv2D, MaxPool2D, Flatten, Dense, Dropout, BatchNormalization
from keras.callbacks import ReduceLROnPlateau, EarlyStopping

with strategy.scope():
    model_alexnet = tf.keras.Sequential([
        # Block 1
        Conv2D(32, (3,3), activation='relu', padding='same', input_shape=(32,32,3)),
        BatchNormalization(),
        MaxPool2D(2,2),

        # Block 2
        Conv2D(64, (3,3), activation='relu', padding='same'),
        BatchNormalization(),
        MaxPool2D(2,2),

        # Block 3
        Conv2D(128, (3,3), activation='relu', padding='same'),
        BatchNormalization(),
        Conv2D(128, (3,3), activation='relu', padding='same'),
        BatchNormalization(),
        Conv2D(64,  (3,3), activation='relu', padding='same'),
        BatchNormalization(),
        MaxPool2D(2,2),

        # Classifier
        Flatten(),
        Dense(256, activation='relu'),
        Dropout(0.5),
        Dense(128, activation='relu'),
        Dropout(0.4),
        Dense(10, activation='softmax')
    ])

    model_alexnet.compile(
        optimizer='adam',
        loss='categorical_crossentropy',
        metrics=['accuracy']
    )

# ==========================================
# STEP 5: Train
# ==========================================
callbacks = [
    ReduceLROnPlateau(monitor='val_accuracy', factor=0.5, patience=3, verbose=1),
    EarlyStopping(monitor='val_accuracy', patience=6, restore_best_weights=True)
]

model_alexnet.fit(
    train_ds,
    epochs=30,
    validation_data=test_ds,
    callbacks=callbacks
)

loss, acc = model_alexnet.evaluate(test_ds)
print("AlexNet TPU Accuracy:", acc)

"""Input
Size: 227 × 227 × 3 (RGB image)



🔹 Conv1
Filters: 96
Kernel: 11×11
Stride: 4
Activation: ReLU
→ Max Pooling


🔹 Conv2
Filters: 256
Kernel: 5×5
→ Max Pooling


🔹 Conv3
Filters: 384
Kernel: 3×3


🔹 Conv4
Filters: 384
Kernel: 3×3


🔹 Conv5
Filters: 256
Kernel: 3×3
→ Max Pooling



🔹 Fully Connected (FC layers)
FC1 → 4096 neurons
FC2 → 4096 neurons
FC3 (Output) → 1000 classes (ImageNet)
Activation: Softmax


🔥 Key Features (VERY IMPORTANT)
✅ 1. ReLU activation
First major CNN to use ReLU
Faster training than sigmoid/tanh
✅ 2. Max Pooling
Reduces spatial size
Keeps important features
✅ 3. Dropout
Prevents overfitting (used in FC layers)
✅ 4. Data Augmentation
Flipping, cropping images
✅ 5. GPU training
One of the first models trained efficiently on GPUs

AlexNet Performance
Achieved test accuracy of ~87.95%
Validation accuracy peaked at ~89.05% (Epoch 3)
Slight drop after further training
Observation:

Better than LeNet due to:
Deeper architecture
Better feature extraction
Slight overfitting observed after Epoch 3

 Key Insight:

Early stopping around Epoch 3–4 would give optimal performance

ZF net
"""

# ⚠️ YOUR BUG: You used Y_train (raw labels) instead of Y_train_alexnet (one-hot)
# ZF-Net shares same data prep so reuse Y_train_alexnet / Y_test_alexnet

model_zf = Sequential([
    # ZF-Net uses larger first filter (7x7) with stride 2
    Conv2D(96, (7,7), strides=2, activation='relu', padding='same', input_shape=(64,64,3)),
    BatchNormalization(),
    MaxPool2D(3,3, strides=2),

    Conv2D(256, (5,5), strides=2, activation='relu', padding='same'),
    BatchNormalization(),
    MaxPool2D(3,3, strides=2),

    Conv2D(384, (3,3), activation='relu', padding='same'),
    BatchNormalization(),

    Conv2D(256, (3,3), activation='relu', padding='same'),
    BatchNormalization(),

    Flatten(),
    Dense(512, activation='relu'),
    Dropout(0.5),
    Dense(256, activation='relu'),
    Dropout(0.4),
    Dense(10, activation='softmax')
])

model_zf.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

callbacks = [
    ReduceLROnPlateau(monitor='val_accuracy', factor=0.5, patience=3, verbose=1),
    EarlyStopping(monitor='val_accuracy', patience=6, restore_best_weights=True)
]

model_zf.fit(
    X_train_resized, Y_train_alexnet,   # ← fixed: use one-hot labels
    epochs=30,
    batch_size=32,
    validation_data=(X_test_resized, Y_test_alexnet),
    callbacks=callbacks
)

loss, acc = model_zf.evaluate(X_test_resized, Y_test_alexnet)
print("ZF-Net Accuracy:", acc)



"""5 Convolution layers
3 Fully Connected layers

👉 Very similar to AlexNet, but with improvements.


| Layer | Filters | Kernel                     | Key Idea               |
| ----- | ------- | -------------------------- | ---------------------- |
| Conv1 | 96      | **7×7** (instead of 11×11) | Better feature capture |
| Conv2 | 256     | 5×5                        | Same                   |
| Conv3 | 384     | 3×3                        | Same                   |
| Conv4 | 384     | 3×3                        | Same                   |
| Conv5 | 256     | 3×3                        | Same                   |


Uses ReLU + MaxPooling (like AlexNet)


Smaller filters in early layer
AlexNet: 11×11 ❌
ZFNet: 7×7 ✅

 Why?

Large filters lose details
Smaller filters capture finer features
 2. Better stride
Reduced stride → less information loss
 3. Feature visualization (VERY IMPORTANT)

 Introduced Deconvolutional Network (DeconvNet)

Helps visualize what CNN is learning
Debugs filters

Achieved test accuracy of ~88.85% (highest among all)
Stable improvement across epochs
Validation accuracy consistently improved

Observation:

Shows better generalization than AlexNet
Improved feature map handling compared to AlexNet

 Key Insight:

ZF-Net provides the best balance between accuracy and stability

VGGnet
"""

from tensorflow.keras.applications import VGG16
from keras.models import Model
from keras.layers import Dense, Flatten, Dropout, BatchNormalization
from keras.optimizers import Adam

# ── Use 96x96 — VGG needs more spatial resolution than 64x64
X_train_vgg = tf.image.resize(X_train_rgb, (96,96))
X_test_vgg  = tf.image.resize(X_test_rgb,  (96,96))

base_model = VGG16(weights='imagenet', include_top=False, input_shape=(96,96,3))

# ── Freeze only early layers, unfreeze last 2 blocks for fine-tuning
for layer in base_model.layers:
    layer.trainable = False

# Unfreeze last 8 layers (block4 + block5)
for layer in base_model.layers[-8:]:
    layer.trainable = True

# ── Better classification head
x = Flatten()(base_model.output)
x = Dense(512, activation='relu')(x)
x = BatchNormalization()(x)
x = Dropout(0.5)(x)
x = Dense(256, activation='relu')(x)
x = Dropout(0.4)(x)
output = Dense(10, activation='softmax')(x)

model_vgg = Model(inputs=base_model.input, outputs=output)

# ── Lower LR for fine-tuning pretrained weights
model_vgg.compile(
    optimizer=Adam(learning_rate=1e-4),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

callbacks = [
    ReduceLROnPlateau(monitor='val_accuracy', factor=0.5, patience=3, verbose=1),
    EarlyStopping(monitor='val_accuracy', patience=6, restore_best_weights=True)
]

model_vgg.fit(
    X_train_vgg, Y_train_alexnet,
    epochs=20,
    batch_size=32,
    validation_data=(X_test_vgg, Y_test_alexnet),
    callbacks=callbacks
)

loss, acc = model_vgg.evaluate(X_test_vgg, Y_test_alexnet)
print("VGGNet Accuracy:", acc)

"""Instead of large filters like AlexNet:

Use many small 3×3 filters stacked together                                                                      Block 1
2 Conv (64 filters)
Max Pool
🔸 Block 2
2 Conv (128 filters)
Max Pool
🔸 Block 3
3 Conv (256 filters)
Max Pool
🔸 Block 4
3 Conv (512 filters)
Max Pool
🔸 Block 5
3 Conv (512 filters)
Max Pool
🔹 Fully Connected Layers
FC1 → 4096
FC2 → 4096
Output → 1000 (Softmax)
 Why 3×3 filters?
 Instead of 1 big filter:
1 × (7×7)
 VGG uses:
3 × (3×3)

✔️ Benefits:

More non-linearity (ReLU applied multiple times)
Fewer parameters
Better feature learning
Visual intuition

Layers go:

Early → edges
Middle → textures
Deep → objects

Achieved test accuracy of ~87.05%
Training accuracy reached ~90%
Validation accuracy plateaued around 87–87.5%

 Observation:

Despite being deeper, performance is slightly lower than ZF-Net
Likely due to:
Insufficient training epochs
High computational complexity
Need for better tuning


VGGNet generally performs better in literature, but here:

performance is limited due to computational constraints and training setup
"""



"""#visualization of CNN"""

# ==========================================
# 1. Import Libraries
# ==========================================
import numpy as np
import matplotlib.pyplot as plt
from keras.datasets import fashion_mnist
from keras.models import Sequential, Model
from keras.layers import Conv2D, MaxPool2D
from keras.layers import Dense, Flatten
from tensorflow.keras.utils import to_categorical

# ==========================================
# 2. Load Dataset
# ==========================================
(X_train, y_train), (X_test, y_test) = fashion_mnist.load_data()

# Normalize data
X_train = X_train.astype('float32') / 255
X_test = X_test.astype('float32') / 255

# Reshape (add channel dimension)
X_train = X_train.reshape(-1, 28, 28, 1)
X_test = X_test.reshape(-1, 28, 28, 1)

# One-hot encoding
Y_train = to_categorical(y_train, 10)
Y_test = to_categorical(y_test, 10)

# ==========================================
# 3. Build Simple CNN Model
# ==========================================
model = Sequential()

# First Convolution Layer
model.add(Conv2D(32, (3,3), activation='relu', input_shape=(28,28,1)))

# First Pooling Layer
model.add(MaxPool2D(pool_size=(2,2)))

# Second Convolution Layer
model.add(Conv2D(64, (3,3), activation='relu'))

# Second Pooling Layer
model.add(MaxPool2D(pool_size=(2,2)))

# Flatten + Output
model.add(Flatten())
model.add(Dense(10, activation='softmax'))

# Compile
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train
model.fit(X_train, Y_train, epochs=10, batch_size=32)


# 👉 Original model:

# Input → Conv → Pool → Conv → Dense → Output

# 👉 New model:

# Input → [Layer1, Layer2, Layer3 outputs]
# ==========================================
# 4. Feature Map Model
# ==========================================
layer_outputs = [layer.output for layer in model.layers[:4]]
feature_map_model = Model(inputs=model.inputs, outputs=layer_outputs)

# ==========================================
# 5. Select One Image
# ==========================================
sample_image = X_test[0]
sample_image = np.expand_dims(sample_image, axis=0)

# ==========================================
# 6. Get Feature Maps
# ==========================================
feature_maps = feature_map_model.predict(sample_image)

# ==========================================
# 7. Visualize Feature Maps
# ==========================================
for layer_index, fmap in enumerate(feature_maps):

    print("Layer", layer_index+1, "Feature Map Shape:", fmap.shape)

    for i in range(6):
        plt.subplot(2, 3, i+1)
        plt.imshow(fmap[0, :, :, i], cmap='gray')
        plt.axis('off')

    plt.show()

"""#Guided Propagation"""

# ==========================================
# 1. Import Libraries
# ==========================================
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.datasets import fashion_mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPool2D, Flatten, Dense

# ==========================================
# 2. Load Dataset
# ==========================================
(X_train, y_train), (X_test, y_test) = fashion_mnist.load_data()

# Normalize
X_train = X_train.astype('float32') / 255
X_test = X_test.astype('float32') / 255

# Add channel dimension
X_train = X_train.reshape(-1,28,28,1)
X_test = X_test.reshape(-1,28,28,1)



# ==========================================
# 3. Build CNN Model
# ==========================================
model = Sequential([
    Conv2D(32, (3,3), activation='relu', input_shape=(28,28,1),padding='same'),
    MaxPool2D((2,2)),

    Conv2D(64, (3,3), activation='relu',padding='same'),
    MaxPool2D((2,2)),

    Flatten(),
    Dense(128, activation='relu'),
    Dense(10, activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# Train
model.fit(X_train, y_train, epochs=15, batch_size=32)

# ==========================================
# 4. Guided ReLU
# ==========================================
@tf.custom_gradient
def guided_relu(x):
    def grad(dy):
        return tf.cast(dy > 0, "float32") * tf.cast(x > 0, "float32") * dy
    return tf.nn.relu(x), grad

# Replace activations
for layer in model.layers:
    if hasattr(layer, 'activation') and layer.activation == tf.keras.activations.relu:
        layer.activation = guided_relu

# ==========================================
# 5. Select Image
# ==========================================
img = X_test[0]
img = np.expand_dims(img, axis=0)

# ==========================================
# 6. Compute Gradients
# ==========================================
input_tensor = tf.convert_to_tensor(img)

with tf.GradientTape() as tape:
    tape.watch(input_tensor)   #Track how output changes w.r.t this input image
    predictions = model(input_tensor)

    class_idx = tf.argmax(predictions[0])
    loss = predictions[:, class_idx]

grads = tape.gradient(loss, input_tensor)[0]

# Normalize gradients
grads = (grads - tf.reduce_min(grads)) / (tf.reduce_max(grads) - tf.reduce_min(grads))

# ==========================================
# 7. Visualization
# ==========================================
plt.figure(figsize=(8,4))

# Original image
plt.subplot(1,2,1)
plt.imshow(X_test[0].reshape(28,28), cmap='gray')
plt.title("Original")
plt.axis('off')

# Guided Backprop
plt.subplot(1,2,2)
plt.imshow(grads.numpy().reshape(28,28), cmap='gray')
plt.title("Guided Backprop")
plt.axis('off')

plt.show()

print(model.layers[0].activation)

"""#Auto Encoder"""

# ==========================================
# 1. Import Libraries
# ==========================================
import numpy as np
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.models import Model
from keras.datasets import fashion_mnist
import matplotlib.pyplot as plt

# ==========================================
# 2. Load and Prepare Data
# ==========================================
(x_train, _), (x_test, _) = fashion_mnist.load_data()

# Normalize (0–255 → 0–1)
x_train = x_train.astype('float32') / 255.
x_test = x_test.astype('float32') / 255.

# Reshape (2D → 1D vector)
# 60000 x 28 x 28 → 60000 x 784
x_train = x_train.reshape((len(x_train), 784))
x_test = x_test.reshape((len(x_test), 784))

# ==========================================
# 3. Define Encoder and Decoder
# ==========================================
input_dim = 784
encoding_dim = 32

# Encoder
input_layer = Input(shape=(input_dim,))
encoded = Dense(encoding_dim, activation='relu')(input_layer)

# Decoder
decoded = Dense(input_dim, activation='sigmoid')(encoded)

# ==========================================
# 4. Create Model
# ==========================================
autoencoder = Model(input_layer, decoded)

# ==========================================
# 5. Compile
# ==========================================
autoencoder.compile(optimizer='adam', loss='binary_crossentropy')

# ==========================================
# 6. Train
# ==========================================
autoencoder.fit(
    x_train, x_train,
    epochs=20,
    batch_size=256,
    shuffle=True,
    validation_data=(x_test, x_test)
)

# ==========================================
# 7. Test
# ==========================================
decoded_imgs = autoencoder.predict(x_test)

# ==========================================
# 8. Visualize
# ==========================================
n = 10
plt.figure(figsize=(20,4))

for i in range(n):
    # Original
    ax = plt.subplot(2, n, i+1)
    plt.imshow(x_test[i].reshape(28,28))
    plt.gray()
    ax.axis('off')

    # Reconstructed
    ax = plt.subplot(2, n, i+1+n)
    plt.imshow(decoded_imgs[i].reshape(28,28))
    plt.gray()
    ax.axis('off')

plt.show()

"""The autoencoder shows a steady decrease in training loss from 0.4147 to 0.2832, indicating effective learning. The validation loss closely follows the training loss, suggesting good generalization without overfitting. Most of the improvement occurs in the initial epochs, with rapid reduction in loss up to around epoch 5. After epoch 10, the loss stabilizes, indicating convergence of the model. The minimal gap between training and validation loss reflects stable and consistent training. Further training beyond epoch 12 results in only marginal improvements. Overall, the model successfully learns compact representations while preserving essential input features."""

# ==========================================
# COMMON DATA LOADING (RUN THIS FIRST)
# ==========================================
import numpy as np
import matplotlib.pyplot as plt
from keras.datasets import fashion_mnist

# Load dataset
(x_train, _), (x_test, _) = fashion_mnist.load_data()

# Normalize
x_train = x_train.astype('float32') / 255.
x_test = x_test.astype('float32') / 255.

# Flatten for Dense AE
x_train_flat = x_train.reshape((len(x_train), 784))
x_test_flat = x_test.reshape((len(x_test), 784))

# Reshape for CNN AE
x_train_cnn = x_train.reshape((len(x_train), 28, 28, 1))
x_test_cnn = x_test.reshape((len(x_test), 28, 28, 1))

# ==========================================
# COMMON DATA LOADING (RUN THIS FIRST)
# ==========================================
import numpy as np
import matplotlib.pyplot as plt
from keras.datasets import fashion_mnist

# Load dataset
(x_train, _), (x_test, _) = fashion_mnist.load_data()

# Normalize
x_train = x_train.astype('float32') / 255.
x_test = x_test.astype('float32') / 255.

# Flatten for Dense AE
x_train_flat = x_train.reshape((len(x_train), 784))
x_test_flat = x_test.reshape((len(x_test), 784))

# Reshape for CNN AE
x_train_cnn = x_train.reshape((len(x_train), 28, 28, 1))
x_test_cnn = x_test.reshape((len(x_test), 28, 28, 1))



# ==========================================
# 2. Define Undercomplete AE
# ==========================================

from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.models import Model

input_layer = Input(shape=(784,))
encoded = Dense(32, activation='relu')(input_layer)
decoded = Dense(784, activation='sigmoid')(encoded)

autoencoder = Model(input_layer, decoded)
autoencoder.compile(optimizer='adam', loss='binary_crossentropy')

autoencoder.fit(x_train_flat, x_train_flat, epochs=20, batch_size=256)

decoded_imgs = autoencoder.predict(x_test_flat)

#over complete
input_layer = Input(shape=(784,))
encoded = Dense(1024, activation='relu')(input_layer)
decoded = Dense(784, activation='sigmoid')(encoded)

autoencoder = Model(input_layer, decoded)
autoencoder.compile(optimizer='adam', loss='binary_crossentropy')

autoencoder.fit(x_train_flat, x_train_flat, epochs=20, batch_size=256)

decoded_imgs = autoencoder.predict(x_test_flat)

"""The undercomplete autoencoder shows a steady reduction in loss from 0.4130 to 0.2830, indicating that it learns compact and meaningful representations by compressing the input data. The improvement is rapid in the initial epochs and stabilizes after around epoch 10, showing convergence. Due to its limited latent space, it focuses only on essential features and avoids memorization.

In contrast, the overcomplete autoencoder achieves a lower final loss of 0.2476, indicating better reconstruction capability. The larger hidden layer allows the model to retain more information, resulting in sharper and more accurate outputs. However, this also increases the risk of the model learning identity mapping instead of meaningful feature extraction.

Overall, the undercomplete autoencoder provides better feature compression and generalization, while the overcomplete autoencoder achieves superior reconstruction at the cost of potential overfitting.

"""



#denoising
import keras
from keras import layers

# Add noise
noise_factor = 0.3
x_train_noisy = x_train_cnn + noise_factor * np.random.normal(size=x_train_cnn.shape)
x_test_noisy = x_test_cnn + noise_factor * np.random.normal(size=x_test_cnn.shape)

x_train_noisy = np.clip(x_train_noisy, 0., 1.)
x_test_noisy = np.clip(x_test_noisy, 0., 1.)

# Model
input_img = keras.Input(shape=(28,28,1))

x = layers.Conv2D(32, (3,3), activation='relu', padding='same')(input_img)
x = layers.MaxPooling2D((2,2), padding='same')(x)
x = layers.Conv2D(32, (3,3), activation='relu', padding='same')(x)
encoded = layers.MaxPooling2D((2,2), padding='same')(x)

x = layers.Conv2D(32, (3,3), activation='relu', padding='same')(encoded)
x = layers.UpSampling2D((2,2))(x)
x = layers.Conv2D(32, (3,3), activation='relu', padding='same')(x)
x = layers.UpSampling2D((2,2))(x)

decoded = layers.Conv2D(1, (3,3), activation='sigmoid', padding='same')(x)

autoencoder = keras.Model(input_img, decoded)
autoencoder.compile(optimizer='adam', loss='binary_crossentropy')

autoencoder.fit(x_train_noisy, x_train_cnn, epochs=15, batch_size=36)

decoded_imgs = autoencoder.predict(x_test_noisy)

"""The training loss decreased steadily from 0.2951 to 0.2703, indicating that the autoencoder successfully learned to reconstruct clean images from noisy inputs. The loss stabilized after several epochs, suggesting convergence."""

import matplotlib.pyplot as plt

n = 10  # number of images to display

plt.figure(figsize=(20, 6))

for i in range(n):
    # Noisy images
    ax = plt.subplot(3, n, i + 1)
    plt.imshow(x_test_noisy[i].reshape(28, 28), cmap='gray')
    plt.title("Noisy")
    plt.axis("off")

    # Reconstructed images
    ax = plt.subplot(3, n, i + 1 + n)
    plt.imshow(decoded_imgs[i].reshape(28, 28), cmap='gray')
    plt.title("Denoised")
    plt.axis("off")

    # Original images
    ax = plt.subplot(3, n, i + 1 + 2*n)
    plt.imshow(x_test_cnn[i].reshape(28, 28), cmap='gray')
    plt.title("Original")
    plt.axis("off")

plt.show()

from sklearn.decomposition import PCA
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.models import Model

# PCA
pca = PCA(n_components=32)
x_train_pca = pca.fit_transform(x_train_flat)
x_test_pca = pca.transform(x_test_flat)
x_test_pca_reconstructed = pca.inverse_transform(x_test_pca)

# Autoencoder
input_layer = Input(shape=(784,))
encoded = Dense(32, activation='relu')(input_layer)
decoded = Dense(784, activation='sigmoid')(encoded)

autoencoder = Model(input_layer, decoded)
autoencoder.compile(optimizer='adam', loss='binary_crossentropy')

autoencoder.fit(x_train_flat, x_train_flat, epochs=10, batch_size=256)

decoded_imgs = autoencoder.predict(x_test_flat)

import matplotlib.pyplot as plt

n = 10
plt.figure(figsize=(20, 8))

for i in range(n):

    # Original
    ax = plt.subplot(4, n, i + 1)
    plt.imshow(x_test_flat[i].reshape(28, 28), cmap='gray')
    plt.title("Original")
    plt.axis("off")

    # PCA Reconstruction
    ax = plt.subplot(4, n, i + 1 + n)
    plt.imshow(x_test_pca_reconstructed[i].reshape(28, 28), cmap='gray')
    plt.title("PCA")
    plt.axis("off")

    # Autoencoder Reconstruction
    ax = plt.subplot(4, n, i + 1 + 2*n)
    plt.imshow(decoded_imgs[i].reshape(28, 28), cmap='gray')
    plt.title("Autoencoder")
    plt.axis("off")

plt.show()

from tensorflow.keras import regularizers

input_layer = Input(shape=(784,))
encoded = Dense(32, activation='relu',
                activity_regularizer=regularizers.l1(1e-4))(input_layer)

decoded = Dense(784, activation='sigmoid')(encoded)

sparse_ae = Model(input_layer, decoded)
sparse_ae.compile(optimizer='adam', loss='binary_crossentropy')

sparse_ae.fit(x_train_flat, x_train_flat, epochs=20, batch_size=256)

decoded_imgs = sparse_ae.predict(x_test_flat)

from tensorflow.keras import regularizers

input_layer = Input(shape=(784,))
encoded = Dense(32, activation='relu',
                activity_regularizer=regularizers.l1(1e-5))(input_layer)
decoded = Dense(784, activation='sigmoid')(encoded)

sparse_autoencoder = Model(input_layer, decoded)
sparse_autoencoder.compile(optimizer='adam', loss='binary_crossentropy')

sparse_autoencoder.fit(x_train_flat, x_train_flat, epochs=30, batch_size=256)

decoded_sparse = sparse_autoencoder.predict(x_test_flat)

import matplotlib.pyplot as plt

n = 10
plt.figure(figsize=(20, 4))

for i in range(n):
    # Original
    ax = plt.subplot(2, n, i + 1)
    plt.imshow(x_test_flat[i].reshape(28, 28), cmap='gray')
    plt.title("Original")
    plt.axis("off")

    # Reconstructed by Sparse Autoencoder
    ax = plt.subplot(2, n, i + 1 + n)
    plt.imshow(decoded_sparse[i].reshape(28, 28), cmap='gray')
    plt.title("Sparse AE")
    plt.axis("off")

plt.show()

"""Sparse Autoencoder:

Loss: The training loss decreased from ~0.6086 to ~0.3311 over 30 epochs. This suggests the regularization effectively promotes sparsity while learning reconstructions.
Performance: The sparsity constraint encourages the network to learn a more distributed representation where only a few neurons are active for any given input, which can lead to better feature extraction and potentially better generalization. Visually, the reconstructed images generally maintain the core features of the originals.

"""

import numpy as np
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.models import Model
from tensorflow.keras import regularizers
from tensorflow.keras.datasets import fashion_mnist

# Load dataset
(x_train, _), (x_test, _) = fashion_mnist.load_data()

# Normalize
x_train = x_train.astype('float32') / 255.
x_test = x_test.astype('float32') / 255.

# Flatten
x_train = x_train.reshape((len(x_train), 784))
x_test = x_test.reshape((len(x_test), 784))

# Model
input_layer = Input(shape=(784,))

encoded = Dense(64, activation='relu',
                activity_regularizer=regularizers.l1(1e-5))(input_layer)

decoded = Dense(784, activation='sigmoid')(encoded)

autoencoder = Model(input_layer, decoded)

autoencoder.compile(optimizer='adam', loss='binary_crossentropy')

# Train
history = autoencoder.fit(
    x_train, x_train,
    epochs=10,
    batch_size=256,
    shuffle=True,
    validation_data=(x_test, x_test)
)

"""### Visualizing Sparse Autoencoder Results"""

decoded_sparse = autoencoder.predict(x_test)
n = 10
plt.figure(figsize=(20, 4))

for i in range(n):
    # Original
    ax = plt.subplot(2, n, i + 1)
    plt.imshow(x_test[i].reshape(28, 28), cmap='gray')
    plt.title("Original")
    plt.axis("off")

    # Reconstructed by Sparse Autoencoder
    ax = plt.subplot(2, n, i + 1 + n)
    plt.imshow(decoded_sparse[i].reshape(28, 28), cmap='gray')
    plt.title("Sparse AE")
    plt.axis("off")

plt.show()

"""### Sparse Autoencoder Observations
1.  The model used L1 regularization on the encoded layer (`activity_regularizer=regularizers.l1(1e-5)`), encouraging sparsity in the latent representation.
2.  Training shows a decrease in loss from approximately 0.58 to 0.35, indicating the model successfully learned to reconstruct inputs while promoting sparsity.
3.  The visualizations confirm that the reconstructed images generally maintain the clarity and essential features of the originals, as seen in `c12b27d7`.
"""

import tensorflow as tf
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.models import Model
from tensorflow.keras.datasets import fashion_mnist

# Load dataset
(x_train, _), (x_test, _) = fashion_mnist.load_data()

# Normalize
x_train = x_train.astype('float32') / 255.
x_test = x_test.astype('float32') / 255.

# Flatten
x_train = x_train.reshape((len(x_train), 784))
x_test = x_test.reshape((len(x_test), 784))

# Model
input_layer = Input(shape=(784,))
encoded = Dense(64, activation='relu')(input_layer)
decoded = Dense(784, activation='sigmoid')(encoded)

autoencoder = Model(input_layer, decoded)

# Contractive loss
lambda_val = 1e-4

def contractive_loss(y_true, y_pred):
    mse = tf.reduce_mean(tf.square(y_true - y_pred))

    # Jacobian approximation
    W = autoencoder.layers[1].kernel
    h = autoencoder.layers[1].output

    contractive = lambda_val * tf.reduce_sum(tf.square(W))

    return mse + contractive

autoencoder.compile(optimizer='adam', loss=contractive_loss)

# Train
autoencoder.fit(
    x_train, x_train,
    epochs=10,
    batch_size=256,
    validation_data=(x_test, x_test)
)

"""### Visualizing Contractive Autoencoder Results"""

import matplotlib.pyplot as plt

decoded_contractive = autoencoder.predict(x_test)
n = 10
plt.figure(figsize=(20, 4))

for i in range(n):
    # Original
    ax = plt.subplot(2, n, i + 1)
    plt.imshow(x_test[i].reshape(28, 28), cmap='gray')
    plt.title("Original")
    plt.axis("off")

    # Reconstructed by Contractive Autoencoder
    ax = plt.subplot(2, n, i + 1 + n)
    plt.imshow(decoded_contractive[i].reshape(28, 28), cmap='gray')
    plt.title("Contractive AE")
    plt.axis("off")

plt.show()

"""# Contractive Autoencoder Observations
 This model utilized a custom contractive_loss function, which includes a penalty on the Frobenius norm of the encoder's weight matrix to encourage robust feature learning.
 The loss significantly decreased from about 0.058 to 0.015, showing that the model effectively minimized the reconstruction error under the contractive constraint.
 As displayed in`bd0ca69e, the reconstructed images are of good quality, suggesting the learned features are stable and less sensitive to minor input variations.
"""